#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3360/payment
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 0000
#  h2:
#    console:
#      enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#
#payment:
#  toss:
#    test_client_api_key : test_ck_yZqmkKeP8gBaYNBAgpeOrbQRxB9l
#    test_secrete_api_key : test_sk_AQ92ymxN34gZb2pNQ7vg8ajRKXvd
#    success_url : "http://localhost:8080/api/v1/payents/toss/success"
#    fail_url : "http://localhost:8080:/api/v1/payments/toss/fail"